# Generated by Django 5.1.1 on 2024-12-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lecture",
            unique_together={("name", "classroom_number", "professor")},
        ),
    ]
